apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: shopease-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shopease-backend
  template:
    metadata:
      labels:
        app: shopease-backend
    spec:
      containers:
        - name: backend
          image: shopease-backend:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: shopease-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: shopease-secret
                  key: DB_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopease-secret
                  key: DB_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopease-secret
                  key: JWT_SECRET
            - name: RAZORPAY_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: shopease-secret
                  key: RAZORPAY_KEY_ID
            - name: RAZORPAY_KEY_SECRET
              valueFrom:
                secretKeyRef:
                  name: shopease-secret
                  key: RAZORPAY_KEY_SECRET
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: shopease-backend
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: shopease-backend
