apiVersion: v1
kind: ConfigMap
metadata:
  name: shopease-config
  labels:
    app: shopease
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "shopease_db"
  SPRING_DATASOURCE_URL: "jdbc:mysql://mysql-service:3306/shopease_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC"
  JWT_EXPIRATION_MS: "86400000"
